import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Prisma-generated client (re-generated by `prisma generate`)
    "src/generated/**",
  ]),
  {
    rules: {
      // Hydration patterns reading localStorage/Notification.permission/etc.
      // are textbook setState-in-effect cases; the rule is too strict for them.
      // Refactoring to useSyncExternalStore adds significant complexity for no
      // correctness benefit, so we downgrade to warning rather than error.
      "react-hooks/set-state-in-effect": "warn",
    },
  },
]);

export default eslintConfig;
